sudo: required
services: 
  - docker

before_install:
  - docker build -t 9873907098/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 9873907098/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "trn-frontend"
  env: "Trn-frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-1-682426607174"
  bucket_path: "trn-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  