name: Dev deployment from Github to AWS
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@main
        
      - name: build the image
        run: docker build -t 9873907098/docker-react -f Dockerfile.dev .
      - name: test the image 
        run: docker run -e CI=true 9873907098/docker-react npm run test
  
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: trn-frontend
          environment_name: Trn-frontend-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-682426607174
          version_label: ${{ github.sha }}
          region: eu-west-1
          deployment_package: deploy.zip
          
